### ISSUE TITLE
SLES-00503 Mega Man X3 / SLPS-00283 Rockman X3 stuck on loading screen

### ISSUE THREAD

**Issue by metasprite** [grumpycoders/pcsx-redux#184] opened 2020-03-15 01:00 UTC
I've tried both Mega Man X3 and Rockman X3, both get stuck on the loading screen after the company logos. Waited 10+ minutes, nothing. Mega Man X4 plays fine on pcsx-redux, and both versions of X3 play fine on Mednafen (loaded via the .cue, which pcsx-redux is incapable of). Changing the BIOS, emulator settings, or game format (iso / multi-track bin / single-track bin) have no effect.

![x3broken](https://user-images.githubusercontent.com/25594046/76693088-470bcc00-6625-11ea-9e40-b2a8deb2205e.png)

**Comment by nicolasnoble** [comment] 2020-03-15 02:00
Was it with the 32 bits or 64 bits version?

**Comment by metasprite** [comment] 2020-03-15 04:02
`pcsx-redux: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, with debug_info, not stripped`

**Comment by wheremyfoodat** [comment] 2021-12-25 15:31
Can't reproduce. Using the PAL version of the game, tested using both the x86-64 dynarec (top) and interpreter (bottom). The loading screen takes a couple of seconds, but nowhere near a minute.
![image](https://user-images.githubusercontent.com/44909372/147388337-c5631a56-510f-4682-9b88-5e8a5ac3c8be.png)
![image](https://user-images.githubusercontent.com/44909372/147388371-c74f3c5b-d4dc-43d7-b0f4-5b44af4faa9d.png)

**Comment by wheremyfoodat** [comment] 2022-01-29 20:51
Closing due to inability to reproduce.

**Closed by wheremyfoodat** 2022-01-29 20:51 UTC
